Repository jtr13/cc21fall2, pull requests merged in 2021-11, with the labels that each got.

#5 add guide on how to integrate R with postgreSQL
  postgresql_r.Rmd
Labels: tutorial

#9 Create statistics_in_r_vs_python.Rmd
  _bookdown.yml
  statistics_in_r_vs_python.Rmd
Labels: cheatsheet

#10 Create video tutorial about apply function in R
  _bookdown.yml
  apply_function_in_r.Rmd
Labels: tutorial

#17 introduction_to_interactive_graphs_in_r
  _bookdown.yml
  introdution_interative_graphs_in_r.Rmd
Labels: tutorial

#28 Python seaborn cheatsheet
  _bookdown.yml
  python_seaborn_cheatsheet.Rmd
  resources/python_seaborn_cheatsheet/Data Visualization with Seaborn.pdf
  resources/python_seaborn_cheatsheet/citations.pdf
Labels: cheatsheet

#29 use python in r
  resources/use_python_in_r/console.png
  resources/use_python_in_r/env.png
  resources/use_python_in_r/envr.png
  resources/use_python_in_r/pythonvsr.png
  resources/use_python_in_r/stats_wl.csv
  using_python_in_r.Rmd
Labels: tutorial

#36 Create Rchess_package_cheatsheet.Rmd
  Rchess_package_cheatsheet.Rmd
  _bookdown.yml
Labels: cheatsheet

#13 cc 17: stock data analysis first commit
  _bookdown.yml
  resources/stock_analysis/PFE.csv
  stock_analysis.Rmd
Labels: tutorial

#26 hypothesis testing
  _bookdown.yml
  hypothesis_testing_cheatsheet.Rmd
Labels: cheatsheet

#27 updated Yuren's Rmd
  _bookdown.yml
  make_r_packages.Rmd
Labels: cheatsheet

#14 Add Video about Data Vis Ordering
  _bookdown.yml
  data_vis_ordering.Rmd
Labels: tutorial

#35 r lattice tutorial
  _bookdown.yml
  r_lattice_tutorial.Rmd
Labels: tutorial

#34 network visualization in r
  _bookdown.yml
  network_visualization_in_r.Rmd
Labels: tutorial

#87 Dplyr tutorial
  _bookdown.yml
  dplyr_tutorial_in_r.Rmd
Labels: tutorial

#31 Update interactive_web_visualizations_for_r_cheatsheet.Rmd
  _bookdown.yml
  interactive_web_visualizations_for_r_cheatsheet.Rmd
  resources/interactive_web_visualizations_for_r_cheatsheet/page1.jpg
  resources/interactive_web_visualizations_for_r_cheatsheet/page2.jpg
Labels: cheatsheet

#20 ggforce
  _bookdown.yml
  ggforce.Rmd
Labels: cheatsheet

#7 Downloading Files
  downloading_files.Rmd
  resources/downloading_files/chicago.rds
  resources/downloading_files/db_sql.sqlite
  resources/downloading_files/output.csv
Labels: tutorial

#18 community contribution
  _bookdown.yml
  gganimate_cheatsheat.Rmd
Labels: cheatsheet

#37 Create statistical_tests_and_parameter_estimations_in_r.Rmd
  _bookdown.yml
  statistical_tests_and_parameter_estimations_in_r.Rmd
Labels: cheatsheet

#57 intro_to_maps_with_ggmap branch request
  _bookdown.yml
  intro_to_maps_with_ggmap.Rmd
  resources/ggmap_tutorial_images/unnamed-chunk-10-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-11-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-12-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-13-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-14-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-6-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-7-1.png
  resources/ggmap_tutorial_images/unnamed-chunk-8-1.png
Labels: tutorial

#56 create file
  _bookdown.yml
  base_r_tidyverse_data_table.Rmd
Labels: tutorial

#95 GGalluvial cheatsheet
  _bookdown.yml
  ggalluvial_cheatsheet.Rmd
Labels: cheatsheet

#19 Analytics consulting intro
  _bookdown.yml
  analytics_consulting_intro.Rmd
Labels: workshop

#108 Create cc_plotly_cheatsheet.Rmd
  _bookdown.yml
  cc_plotly_cheatsheet.Rmd
Labels: cheatsheet

#64 Add raincloud plot tutorial
  _bookdown.yml
  raincloud_plot_tutorial.rmd
  resources/raincloud_plot_tutorial/bank.RData
  resources/raincloud_plot_tutorial/walmart_monthly_sales.RData
Labels: tutorial

#49 yc4014 pushing finished proj
  _bookdown.yml
  intro_to_dygraph.Rmd
  resources/intro_to_dygraph/cpi.xlsx
Labels: tutorial, changes requested

#75 streamlit tutorial
  _bookdown.yml
  streamlit_tutorial.rmd
Labels: tutorial

#84 Concept r python cheatsheet
  _bookdown.yml
  concept_r_python_cheatsheet.Rmd
Labels: cheatsheet, changes requested

#58 Hive Plots with R ggraph and HiveR explanation
  _bookdown.yml
  hive_plots_ggraph_hiver.Rmd
Labels: tutorial

#125 Create data_visualization_packages_in_r.jpg
  _bookdown.yml
  data_visualization_packages_in_r.Rmd
  resources/data_visualization_packages_in_r/data_visualization_packages_in_r.jpg
Labels: cheatsheet

#42 GitHub submission for introduction_to_xai_in_r.Rmd
  _bookdown.yml
  introduction_to_xai_in_r.Rmd
Labels: tutorial

#142 MingyueXu add
  _bookdown.yml
  tutorial_gg_cleveland.Rmd
Labels: tutorial

#118 initial commit
  _bookdown.yml
  neuralnet_r_tutorial.Rmd
Labels: tutorial

#136 Zihao Zhang's Rmd file
  _bookdown.yml
  introduction_to_pyecharts_package.Rmd
Labels: data_visualizations

#50 From dplyr to pandas and back
  _bookdown.yml
  from_dplyr_to_pandas_and_back.Rmd
  resources/yujia_resources/Pandas.png
  resources/yujia_resources/dplyr.png
  resources/yujia_resources/yellowcab.csv
Labels: tutorial

#65 I would like to upload my CC to github.
  _bookdown.yml
  readable_plots.Rmd
Labels: tutorial

#85 spatial data analysis
  _bookdown.yml
  resources/spatial_data_analysis/Picture1.png
  resources/spatial_data_analysis/Picture10.png
  resources/spatial_data_analysis/Picture11.png
  resources/spatial_data_analysis/Picture12.png
  resources/spatial_data_analysis/Picture13.png
  resources/spatial_data_analysis/Picture14.png
  resources/spatial_data_analysis/Picture15.png
  resources/spatial_data_analysis/Picture16.png
  resources/spatial_data_analysis/Picture17.png
  resources/spatial_data_analysis/Picture18.png
  resources/spatial_data_analysis/Picture19.png
  resources/spatial_data_analysis/Picture2.png
  resources/spatial_data_analysis/Picture20.png
  resources/spatial_data_analysis/Picture21.png
  resources/spatial_data_analysis/Picture22.png
  resources/spatial_data_analysis/Picture23.png
  resources/spatial_data_analysis/Picture24.png
  resources/spatial_data_analysis/Picture25.png
  resources/spatial_data_analysis/Picture3.png
  resources/spatial_data_analysis/Picture4.png
  resources/spatial_data_analysis/Picture5.png
  resources/spatial_data_analysis/Picture6.png
  resources/spatial_data_analysis/Picture7.png
  resources/spatial_data_analysis/Picture8.png
  resources/spatial_data_analysis/Picture9.png
  spatial_data_analysis.Rmd
Labels: tutorial

#8 esquisse_cheatsheet by Hongtao Jiang(hj2554)
  _bookdown.yml
  esquisse_cheatsheet.Rmd
  resources/esquisse_cheatsheet/esquisse_cheatsheet.jpg
Labels: cheatsheet

#137 Tutorial for data visualization in Python and its comparison with R
  _bookdown.yml
  python_vs_r_graph.Rmd
Labels: tutorial

#130 review sheet for r code and data transformation
  _bookdown.yml
  review_sheet_for_r_code_and_data_transformation.Rmd
Labels: cheatsheet

#52 Upload the base r tutorial .Rmd file
  _bookdown.yml
  base_r_tutorial.Rmd
Labels: tutorial, changes requested

#68 Add python_altair_tutorial.Rmd
  _bookdown.yml
  python_altair_tutorial.Rmd
Labels: tutorial

#114 complete r_vs_python zc2619
  _bookdown.yml
  r_vs_python_plots.Rmd
  resources/r_vs_python/covid_africa.csv
  resources/r_vs_python/pic1.png
  resources/r_vs_python/pic10_heat.png
  resources/r_vs_python/pic11_mo.png
  resources/r_vs_python/pic2_hist.png
  resources/r_vs_python/pic3_hist.png
  resources/r_vs_python/pic4_bar.png
  resources/r_vs_python/pic5_bar.png
  resources/r_vs_python/pic6_box.png
  resources/r_vs_python/pic7_scatter.png
  resources/r_vs_python/pic8_parcoord.png
  resources/r_vs_python/pic9.png
  resources/r_vs_python/student_performance.csv
Labels: data_visualizations

#131 Create r_to_python_plot_tutorial.Rmd
  _bookdown.yml
  r_to_python_plot_tutorial.Rmd
Labels: tutorial

#117 Create models_and_prediction_evaluation
  _bookdown.yml
  models_and_prediction_evaluation.Rmd
Labels: tutorial

#4 Create interactive_dygraphs.Rmd
  _bookdown.yml
  interactive_dygraphs.Rmd
Labels: tutorial

#107 r_with_python
  _bookdown.yml
  r_with_python.Rmd
  resources/r_with_python/Hello.py
  resources/r_with_python/Rplot.png
  resources/r_with_python/console1.png
  resources/r_with_python/console2.png
  resources/r_with_python/plot.py
Labels: tutorial, changes requested

#15 Scrape Twitter with R
  _bookdown.yml
  resources/Scrape_Twitter_R/f1.png
  resources/Scrape_Twitter_R/f2.png
  resources/Scrape_Twitter_R/f3.png
  resources/Scrape_Twitter_R/f4.png
  scrape_twitter_r.Rmd
Labels: tutorial, changes requested

#69 Add python visualization tutorial from Jingxiang Zhang
  _bookdown.yml
  python_visualization_tutorial.Rmd
Labels: tutorial

#60 Adding materials for map_of_r_world project
  _bookdown.yml
  map_of_r_world.Rmd
  resources/map_of_r_world/r_world_2d_compressed.png
  resources/map_of_r_world/r_world_3d_static.png
Labels: project

#98 Plots python seaborn matplotlib
  _bookdown.yml
  plots_python_seaborn_matplotlib.Rmd
  resources/plots_python_seaborn_matplotlib/Understand Data with Plots.ipynb
  resources/plots_python_seaborn_matplotlib/Understand Data with Plots.pdf
Labels: data_visualizations

#120 Submission for community contribution
  _bookdown.yml
  alluvial_diagrams_and_their implementation_in_r.Rmd
Labels: project

#138 Create gganimate tutorial
  _bookdown.yml
  intro_to_gganimate.Rmd
Labels: tutorial

#79 Add nbastatr_tutorial for contribution
  _bookdown.yml
  nbastatr_tutorial.Rmd
Labels: tutorial

#132 add submission
  _bookdown.yml
  edav_cc.Rmd
Labels: cheatsheet

#150 Ruoxi Liu and Ziyu Fang's Community Contribution
  _bookdown.yml
  ggplot2_cheatsheet.Rmd
Labels: cheatsheet

#103 Initial commit
  _bookdown.yml
  rstudio_cheatsheet.Rmd
Labels: cheatsheet

#111 D3 visualizations in r cheat sheet
  _bookdown.yml
  d3_visualizations_in_r_cheatsheet.Rmd
Labels: cheatsheet

#148 Community Contribution - MTemplates (New Package) - mj3038
  _bookdown.yml
  mtemplates_mj3038.rmd
Labels: tutorial, changes requested

#38 introduction_to_time_series_analysis_in_r.Rmd
  _bookdown.yml
  introduction_to_time_series_analysis_in_r.Rmd
Labels: tutorial, changes requested

#76 Add storytelling_with_data.Rmd
  _bookdown.yml
  storytelling_with_data.Rmd
Labels: tutorial

#139 r_torch_tutorial
  _bookdown.yml
  r_torch_tutorial.Rmd
Labels: tutorial

#48 first commit
  dataframe_operation_tutorial.Rmd
  resources/Rayzyz_resources/111.jpeg
  resources/Rayzyz_resources/222.png
  resources/Rayzyz_resources/333.jpeg
  resources/Rayzyz_resources/data.csv
Labels: tutorial

#123 add correlogram_calendar_heatmap_slopegram_tutorial.Rmd
  _bookdown.yml
  correlogram_calendar_heatmap_slopegram_tutorial.Rmd
Labels: tutorial

#134 Add a tutorial: r_recursive_codes_and_som.Rmd
  _bookdown.yml
  r_recursive_codes_and_som.Rmd
Labels: tutorial

#33 Community Contribution
  _bookdown.yml
  tutorial_of_three_ggplot2_based_packages.Rmd
Labels: tutorial

#25 Adding colors cheatsheet
  _bookdown.yml
  colors.Rmd
  resources/colors/colors.jpg
Labels: cheatsheet

#67 Data_Visualization_R_Shiny uploaded
  _bookdown.yml
  data_visualization_r_shiny.Rmd
Labels: changes requested, project

#129 Tutorial for ggvis and its Comparison with ggplot2
  _bookdown.yml
  ggvis_ggplot2_graphs.Rmd
Labels: tutorial

#146 first message
  _bookdown.yml
  r_and_python_visualization.Rmd
Labels: data_visualizations

#72 cc github submission (zehui wu)
  _bookdown.yml
  feature_selection_in_r.Rmd
Labels: tutorial, changes requested

#46 upload community distribution rmd
  _bookdown.yml
  r_tutorial_cheatsheet.Rmd
Labels: cheatsheet

#113 Introduction of ggpubr
  _bookdown.yml
  brief_introduction_of_ggpubr.Rmd
Labels: tutorial, changes requested

#121 Create cheat sheet base_r_data_organization_visualization.Rmd
  _bookdown.yml
  base_r_data_organization_visualization.Rmd
Labels: cheatsheet

#61 Map Visualization with R tutorial
  _bookdown.yml
  map_visualization.Rmd
  resources/map_visualization/map_anim.gif
Labels: tutorial

#91 R_datasets
  _bookdown.yml
  r_datasets.Rmd
  resources/r_datasets/r_datasets_cheatsheet.pdf
Labels: cheatsheet, changes requested

#92 cheatsheet_plotly
  _bookdown.yml
  plotly_cheatsheet.Rmd
Labels: cheatsheet, changes requested

#81 Add common commands of github tutorial
  _bookdown.yml
  common_github_commands.Rmd
Labels: tutorial

#94 super_ggformat_project
  _bookdown.yml
  super_ggformat_project.Rmd
Labels: r_package

#71 Create tidyverse.Rmd
  _bookdown.yml
  tidyverse.Rmd
Labels: cheatsheet, changes requested

#82 init radar chart tutorial with pictures
  _bookdown.yml
  resources/radar_chart_pic/browser.png
  resources/radar_chart_pic/check.png
  resources/radar_chart_pic/choose.png
  resources/radar_chart_pic/cmd.png
  resources/radar_chart_pic/detail.png
  resources/radar_chart_pic/directory.png
  resources/radar_chart_pic/github.png
  resources/radar_chart_pic/tar.png
  tutorial_of_radar_chart.Rmd
Labels: tutorial, changes requested

#32 r_shiny_tutorial
  _bookdown.yml
  r_shiny_tutorial.Rmd
  resources/r_shiny_tutorial/1.png
  resources/r_shiny_tutorial/10.png
  resources/r_shiny_tutorial/11.png
  resources/r_shiny_tutorial/12.png
  resources/r_shiny_tutorial/13.png
  resources/r_shiny_tutorial/14.png
  resources/r_shiny_tutorial/2.png
  resources/r_shiny_tutorial/3.png
  resources/r_shiny_tutorial/4.png
  resources/r_shiny_tutorial/5.png
  resources/r_shiny_tutorial/6.png
  resources/r_shiny_tutorial/7.png
  resources/r_shiny_tutorial/8.png
  resources/r_shiny_tutorial/9.png
Labels: tutorial

#66 introduction to R Markdown 1st version
  _bookdown.yml
  introduce_rmarkdown.Rmd
  resources/Introduction_to_RMarkdown/cute_kitten.jpg
Labels: tutorial

#144 Session on RGL package
  _bookdown.yml
  rgl_package.Rmd
Labels: workshop

#39 adding my cc project to the main repo
  _bookdown.yml
  learn_sql_using_its_r_translation.Rmd
Labels: cheatsheet

#47 Added .Rmd and images in resources folder
  _bookdown.yml
  animate_time_series.Rmd
  resources/animate_time_series/AdvancedAnimate.gif
  resources/animate_time_series/Animate.gif
  resources/animate_time_series/dashboard.PNG
Labels: tutorial

#70 Mridul Gupta added RMD and data file
  _bookdown.yml
  dlookr.Rmd
  rollingsales_manhattan.xlsx
Labels: tutorial

#126 Urca: Unit Root Test and Cointegration Test tutorial
  _bookdown.yml
  urca_unitroottest_cointegrationtest.Rmd
Labels: tutorial

#110 Add pygal tutorial
  _bookdown.yml
  pygal_tutorial.Rmd
Labels: tutorial

#93 comparing excel and r
  _bookdown.yml
  comparing_excel_and_r.Rmd
Labels: tutorial

#55 Joining and reshaping in r
  _bookdown.yml
  joining_and_reshaping_in_r.Rmd
  resources/joining_and_reshaping_in_r/join_pic.jpg
Labels: tutorial

#6 Running Sql Queries on Dataframes (Community contribution Group 11).
  _bookdown.yml
  running_sql_queries_on_dataframes.Rmd
Labels: tutorial

#155 Community Contribution Rmd file and pdf cheat sheet about stringr
  _bookdown.yml
  resources/stringr_cheatsheet/stringr_cheatsheet.pdf
  stringr_cheatsheet.Rmd
Labels: cheatsheet

#135 First attempt
  _bookdown.yml
  tidyver_help.Rmd
Labels: tutorial, changes requested

#154 Add animate_your_plots.Rmd
  _bookdown.yml
  animate_your_plots.Rmd
Labels: tutorial

#116 Add ggalluvial_cheatsheet
  _bookdown.yml
  ggalluvial_cheatsheet2.Rmd
Labels: cheatsheet, changes requested

#156 Community Contribution Rmd file
  _bookdown.yml
  cheatsheet_pandas_baser_tidyverse.Rmd
Labels: cheatsheet

#162 cleanup on sugggestions
  intro_to_log_transformation.Rmd
  resources/intro_to_log_transformation/Explanation.pdf
  resources/intro_to_log_transformation/intro_log_transf_final.pdf
Labels: cheatsheet

#124 Upload project base_r_ggplot2_python_graph
  base_r_ggplot2_python_graph.Rmd
  resources/base_r_ggplot2_python_graph/README.txt
  resources/base_r_ggplot2_python_graph/symbol_image.png
Labels: cheatsheet

#141 add geospatial_data_visualization.rmd
  geospatial_data_visualization.Rmd
Labels: data_visualizations

#83 Adding for Sharmi Mathur and Ayush Baral
  score_hundred_cheatsheet.Rmd
Labels: cheatsheet

#63 add my scatterplots_cheatsheet and scatterplots cheatsheet pdf under resources
  resources/scatterplots_cheatsheet/scatterplots.pdf
  scatterplots_cheatsheet.Rmd
Labels: cheatsheet

#53 Create cc_instruction_for_new.Rmd
  _bookdown.yml
  cc_instruction_for_new.Rmd
Labels: tutorial, changes requested

#12 First commit. Group28_anova_tutorial
  _bookdown.yml
  anova_tutorial.Rmd
  anova_tutorial_revised.Rmd
Labels: tutorial

#16 Add "Base R String Operations Cheatsheet" to the repo
  _bookdown.yml
  base_r_string_operations_cheatsheet.Rmd
Labels: cheatsheet

#43 Add data_manipulation_cheatsheet to the repo
  _bookdown.yml
  data_manipulation_cheatsheet.Rmd
Labels: cheatsheet

#89 ggplot_matplotlib_cheatsheet
  _bookdown.yml
  ggplot_matplotlib_cheatsheet.Rmd
  resources/ggplot_Matplotlib_cheatsheet/ggplot_Matplotlib_cheatsheet.pdf
Labels: cheatsheet, changes requested

#119 Add files via upload
  _bookdown.yml
  ggplot_base_r_graph_analysis.Rmd
Labels: changes requested, data_visualizations

#161 Add files via upload
  _bookdown.yml
  ggplot2_in_python.Rmd
Labels: tutorial

#22 Adding Predictive Analytics RMD file
  _bookdown.yml
  predictive-analytics-r.Rmd
Labels: tutorial, changes requested

#176 Group 31
  _bookdown.yml
  color_selection_ggplot.Rmd
Labels: tutorial

#173 Update scatterplots_cheatsheet.Rmd
  _bookdown.yml
  scatterplots_cheatsheet.Rmd
Labels: cheatsheet

#145 First try to commit, EDAV CC
  _bookdown.yml
  improved_density_estimation.Rmd
Labels: data_visualizations

#127 data_vis_for_ranking
  _bookdown.yml
  data_vis_for_ranking.Rmd
Labels: tutorial

#147 Self learning
  _bookdown.yml
  self_learning.Rmd
Labels: tutorial, changes requested

#97 Tutorial on how to use mongodb with r github submission
  _bookdown.yml
  mongodb_and_r.Rmd
  resources/mongodb_and_r/collection_appearance.png
  resources/mongodb_and_r/connection_string.png
  resources/mongodb_and_r/dataset_editted.txt
  resources/mongodb_and_r/mongodb_create_database.png
Labels: tutorial, changes requested

#21 Plotting graph with R v.s. Python
  _bookdown.yml
  r_python_graph_code.Rmd
Labels: tutorial

#24 rdoc_alfred_workflow by dsg2157
  _bookdown.yml
  rdoc_alfred_workflow.Rmd
Labels: tutorial

#99 Added File for Data Frame ReshapeTutorial
  _bookdown.yml
  data_frame_reshape.Rmd
Labels: tutorial

#151 Add theme_columbia.Rmd project
  _bookdown.yml
  theme_columbia.Rmd
Labels: changes requested, data_visualizations
